# Generated by Django 5.0.6 on 2025-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_specialization',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
